//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blagodat.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int IDHIistory { get; set; }
        public string UserLogin { get; set; }
        public System.DateTime LastDate { get; set; }
        public string EnterType { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
